### ISSUE TITLE
Delivery problem

### ISSUE THREAD

**Issue by x893** [Kevincoooool/KS_Diy_Link#2]
Hello,
thanks for this project !
I try to buy devices from Taobao but not dedlivery to my country. Possible buy from Aliexpress or other shop ?

Best regards
Mitek

**Comment by majianjia** [comment]
> 
> 
> Hello,
> thanks for this project !
> I try to buy devices from Taobao but not dedlivery to my country. Possible buy from Aliexpress or other shop ?
> 
> Best regards
> Mitek

It is nice to see you here!
Thanks for your initial works on RU forum and your post on your blog.
I can buy it from an agent (base in China) then send to your address.
If you need it, please contact me.

**Comment by Kevincoooool** [comment]
Hi，I can give you the jlink by free，if you got a taobao account

---Original---

**Comment by x893** [comment]
Thanks Kevin !
Yes, i have TaoBao account.
x89300
I can't find link on Taobao to send message to your shop.

**Comment by Kevincoooool** [comment]
I think you can learn about dotdotbuy...

**Comment by x893** [comment]
OK, i'll learn.
I think some delivery problems with virus situation.
I design board with both microUSB and USB-A.

![JLink9](https://user-images.githubusercontent.com/211750/78637770-baff6400-78b3-11ea-849d-d0ecc848fd86.jpg)

Thanks for your project !

**Comment by x893** [comment]
Thanks Kevin !
i build JLinks with USB-A and microUSB (above) and both works fine.
Best wishes

![jlink-1](https://user-images.githubusercontent.com/211750/82107247-bf2e6500-972e-11ea-8c2b-09ce7d1f811c.jpg)
![jlink-2](https://user-images.githubusercontent.com/211750/82107250-c2c1ec00-972e-11ea-96ab-fdea4b8962d3.jpg)

**Comment by Kevincoooool** [comment]
> Thanks Kevin !
> i build JLinks with USB-A and microUSB (above) and both works fine.
> Best wishes
> 
> ![jlink-1](https://user-images.githubusercontent.com/211750/82107247-bf2e6500-972e-11ea-8c2b-09ce7d1f811c.jpg)
> ![jlink-2](https://user-images.githubusercontent.com/211750/82107250-c2c1ec00-972e-11ea-96ab-fdea4b8962d3.jpg)

Hey,Did you find the JlinkOB firmware in JlinkARM.dll before? I have made a JLink OB SAM3U128 board now, but there is no bootloader, can you help me find it?

**Comment by x893** [comment]
Hi, I never use SAM3 before. I see that some SAM3U128 firmwares presents in JLinkARM.dll but without bootloader. Before i havn't JLink bootloader (thank you for publish) i use system bootloader and upload firmware via ST FlashProgrammer. May be this way available for SAM3U.
