### ISSUE TITLE
无法连接到STM32F030C8T6

### ISSUE THREAD

**Issue by johnzhy** [Kevincoooool/KS_Diy_Link#3]
可以连接到STM32F1、F2，但是连接STM32F030C8T6的时候无法连接，MDK识别不到芯片，J-Flash连接的时候出现以下故障信息
Connecting ...
 - Connecting via USB to J-Link device 0
 - J-Link firmware: J-Link V9 compiled Dec 13 2019 11:14:50
 - Device "STM32F030C8" selected.
 - Target interface speed: 4000 kHz (Fixed)
 - VTarget = 3.306V
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - STM32 (connect): Can not attach to CPU. Trying connect under reset.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - STM32 (connect): Can not attach to CPU. Trying connect under reset.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - RESET (pin 15) high, but should be low. Please check target hardware.
 - ERROR: STM32: Connecting to CPU via connect under reset failed.
 - ERROR: Failed to connect.
Could not establish a connection to target.

**Comment by Kevincoooool** [comment]
我用来给STM32F030F4P6是正常是下载的，检查一下连线？

**Comment by johnzhy** [comment]
应该可以排除连线问题。
用diy-jlink可以给STM32F103RE、STM32F205RE正常下载程序，但是却无法识别STM32F030C8。
无法识别的这个STM32F030C8板子，可以被我手里别的jlink、STlink正常识别、下载、仿真。

**Comment by Kevincoooool** [comment]
四根线都连上、3V3 DIO CLK GND   你的F0是不是低功耗带RST引脚的？现在的硬件RST引脚无法正常使用

**Comment by johnzhy** [comment]
我手里正好有STM32F030F4P6，确实也可以正常连接。
STM32F030C8应该不是低功耗版本吧，和STM32F030F4P6一样的吧

**Comment by Kevincoooool** [comment]
不是  要看C8T6的程序有没有进低功耗

**Comment by johnzhy** [comment]
哦哦，明白你的意思了。那我把芯片程序擦除，看看能否连上就行吧

**Comment by Kevincoooool** [comment]
是的，本身进了低功耗模式后必须要RST复位才能连接的

**Comment by johnzhy** [comment]
刚刚试过，先用别的Jlink通过J-Flash擦除芯片，然后用DIY-Jlink还是连不上，错误信息还是一样的。

**Comment by johnzhy** [comment]
对了，别的Jlink连接的时候也是四根线，没有连RST引脚

**Comment by Kevincoooool** [comment]
那就不太清楚了- -我给每个F0下程序都没问题

**Comment by johnzhy** [comment]
找到问题了，我对比了一下STM32F030C8的板子，这个板子的SWDIO和SWCLK引脚上都串联了一个100欧姆的电阻，其他可以连上的板子都没有，我把这两个电阻短路后就可以连上了。

**Comment by Kevincoooool** [comment]
jlink上本身已经串联了一个100欧的电阻了
